spring.application.name=restaurante

# CONEXION A BASE DE DATOS (Mapeo Inteligente Local / Railway)
spring.datasource.url=jdbc:mysql://localhost:3306/restauranteweb
spring.datasource.username=root
spring.datasource.password=BRAYAN123456@

# CONFIGURACION JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# CONTROL DE PESO MULTIPART (Vouchers de Auditoria)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# INTEGRACION API DE FACTURACION ELECTRONICA (SUNAT / RENIEC)
miapi.facturacion.url.comprobante=https://miapi.cloud/apifact/invoice/create
miapi.facturacion.url.nota=https://miapi.cloud/apifact/note/create
miapi.facturacion.token=c97178e1-cb5e-4cd3-8fb0-427060272768

# URLs para consultas de documentos (LaJama Proxy)
miapi.url.ruc=https://miapi.cloud/v1/ruc/
miapi.url.dni=https://miapi.cloud/v1/dni/

# El token unificado que buscará el controlador
miapi.token=c97178e1-cb5e-4cd3-8fb0-427060272768
miapi.cloud.token=c97178e1-cb5e-4cd3-8fb0-427060272768

# ALMACENAMIENTO DE IMAGENES (Referencia Circular Saneada)
app.images.base-url=https://res.cloudinary.com/dyjnbddit/image/upload/    
app.cloudinary.url=cloudinary://375514197911376:KaT8FThYLsWUif60pHsNfchJmpU@dyjnbddit

# ? CONFIGURACIÓN DE CORREO ELECTRÓNICO (SMTP GMAIL)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dashpan806@gmail.com
spring.mail.password=yrjoenydsgfhchxo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# CONFIGURACIÓN DE ENTORNO (Cambiar al desplegar en Railway)
app.base-url=http://localhost:8080